In [1]:
import pandas as pd
df_laptops = pd.read_csv('../laptop_price.csv', encoding='latin1')
df_laptops.head()

   laptop_ID Company      Product  ...  OpSys  Weight Price_euros
0          1   Apple  MacBook Pro  ...  macOS  1.37kg     1339.69
1          2   Apple  Macbook Air  ...  macOS  1.34kg      898.94
2          3      HP       250 G6  ...  No OS  1.86kg      575.00
3          4   Apple  MacBook Pro  ...  macOS  1.83kg     2537.45
4          5   Apple  MacBook Pro  ...  macOS  1.37kg     1803.60

[5 rows x 13 columns]

In [3]:
# Sorting according to Company and Inches (Ascending)
df_laptops = df_laptops.sort_values(['Company', 'Inches'])

In [ ]:
#dropping duplicates, Keeping Smallest Screen Size
df_laptops.drop_duplicates(['Company'], keep='first', ignore_index=True)[['Company', 'Inches']]

      Company  Inches
0        Acer    11.6
1       Apple    11.6
2        Asus    11.6
3       Chuwi    12.3
4        Dell    11.6
5     Fujitsu    15.6
6      Google    12.3
7          HP    11.6
8      Huawei    13.0
9          LG    14.0
10     Lenovo    10.1
11        MSI    14.0
12   Mediacom    11.6
13  Microsoft    13.5
14      Razer    12.5
15    Samsung    11.6
16    Toshiba    12.5
17       Vero    13.3
18     Xiaomi    13.3

In [7]:
#dropping duplicates, Keeping Biggest Screen Size
df_laptops.drop_duplicates(['Company'], keep='last', ignore_index=True)[['Company', 'Inches']]

      Company  Inches
0        Acer    17.3
1       Apple    15.4
2        Asus    17.3
3       Chuwi    15.6
4        Dell    17.3
5     Fujitsu    15.6
6      Google    12.3
7          HP    17.3
8      Huawei    13.0
9          LG    15.6
10     Lenovo    17.3
11        MSI    18.4
12   Mediacom    14.0
13  Microsoft    13.5
14      Razer    17.3
15    Samsung    15.6
16    Toshiba    15.6
17       Vero    14.0
18     Xiaomi    15.6