In [1]:
import pandas as pd

## Import a .csv file from a website
<br>
<br>
Target Link: https://football-data.co.uk/englandm.php

In [3]:
#Reading a file from a website
df_premier25 = pd.read_csv('https://football-data.co.uk/mmz4281/2526/E0.csv')
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
5,E0,16/08/2025,17:30,Wolves,Man City,0,4,A,0,2,...,1.98,1.88,2.07,1.86,2.04,1.88,1.91,1.81,2.05,1.94
6,E0,17/08/2025,14:00,Chelsea,Crystal Palace,0,0,D,0,0,...,1.85,2.00,1.74,2.21,1.85,2.03,1.79,1.97,1.88,2.12
7,E0,17/08/2025,14:00,Nott'm Forest,Brentford,3,1,H,3,0,...,1.88,1.98,2.18,1.76,1.91,1.98,1.86,1.89,1.96,2.03
8,E0,17/08/2025,16:30,Man United,Arsenal,0,1,A,0,1,...,1.88,1.98,1.91,2.01,1.93,1.98,1.86,1.89,2.00,1.99
9,E0,18/08/2025,20:00,Leeds,Everton,1,0,H,0,0,...,2.05,1.80,2.02,1.90,2.05,1.86,1.91,1.78,2.14,1.86

In [5]:
#Renaming Columns
df_premier25.rename(columns={'FTHG': 'home_goals',
                             'FTAG' : 'away_goals'}, inplace=True)
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
5,E0,16/08/2025,17:30,Wolves,Man City,0,4,A,0,2,...,1.98,1.88,2.07,1.86,2.04,1.88,1.91,1.81,2.05,1.94
6,E0,17/08/2025,14:00,Chelsea,Crystal Palace,0,0,D,0,0,...,1.85,2.00,1.74,2.21,1.85,2.03,1.79,1.97,1.88,2.12
7,E0,17/08/2025,14:00,Nott'm Forest,Brentford,3,1,H,3,0,...,1.88,1.98,2.18,1.76,1.91,1.98,1.86,1.89,1.96,2.03
8,E0,17/08/2025,16:30,Man United,Arsenal,0,1,A,0,1,...,1.88,1.98,1.91,2.01,1.93,1.98,1.86,1.89,2.00,1.99
9,E0,18/08/2025,20:00,Leeds,Everton,1,0,H,0,0,...,2.05,1.80,2.02,1.90,2.05,1.86,1.91,1.78,2.14,1.86

## Read .csv from multiple URLS with Pandas
<br>
Link: root + season + league

In [9]:
#Link Structure
# https://football-data.co.uk/mmz4281/2526/E0.csv
#https://football-data.co.uk/mmz4281/2526/E1.csv

"https://football-data.co.uk/mmz4281/" + "2526" + "/" + "E1" + ".csv"

'https://football-data.co.uk/mmz4281/2526/E1.csv'

In [10]:
#Create a Root Variable
root = "https://football-data.co.uk/mmz4281/"

### Multiple Leagues
<br>
https://football-data.co.uk/mmz4281/2526/E0.csv
<br>
https://football-data.co.uk/mmz4281/2526/E1.csv
<br>
https://football-data.co.uk/mmz4281/2526/E2.csv
<br>
https://football-data.co.uk/mmz4281/2526/E3.csv
<br>
https://football-data.co.uk/mmz4281/2526/EC.csv

In [14]:
#Creating a list og leagues
leagues = ["E0", "E1", "E2", "E3", "EC"]
frames = []

#Looping through leagues, read multiple csv and append it to the list
for league in leagues:
    df = pd.read_csv(root + "2526" + "/" + league + ".csv")
    frames.append(df)

In [15]:
#lenght of frames
len(frames)

5

In [17]:
#Show 1st, 2nd and 3rd Element
frames[2]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E2,01/08/2025,20:00,Luton,AFC Wimbledon,1,0,H,0,0,...,1.93,1.93,1.93,1.95,1.98,1.93,1.91,1.82,1.94,2.01
1,E2,02/08/2025,12:30,Cardiff,Peterboro,2,1,H,0,1,...,1.85,2.00,1.87,2.03,1.90,2.00,1.85,1.88,1.93,2.04
2,E2,02/08/2025,15:00,Blackpool,Stevenage,2,3,A,1,2,...,1.93,1.93,1.94,1.94,1.94,1.93,1.84,1.87,1.94,2.04
3,E2,02/08/2025,15:00,Bradford,Wycombe,2,1,H,2,0,...,1.73,2.08,1.90,1.99,1.77,2.20,1.72,2.02,1.80,2.22
4,E2,02/08/2025,15:00,Burton,Mansfield,2,1,H,1,0,...,2.00,1.85,1.69,2.26,2.00,1.85,1.93,1.79,2.04,1.93
5,E2,02/08/2025,15:00,Doncaster,Exeter,1,0,H,0,0,...,2.03,1.83,2.08,1.83,2.03,1.88,1.92,1.82,1.98,1.97
6,E2,02/08/2025,15:00,Huddersfield,Leyton Orient,3,0,H,1,0,...,1.83,2.03,1.96,1.93,1.83,2.03,1.74,1.97,1.86,2.15
7,E2,02/08/2025,15:00,Lincoln,Reading,2,0,H,1,0,...,2.00,1.85,2.03,1.87,2.00,1.85,1.94,1.81,2.04,1.95
8,E2,02/08/2025,15:00,Plymouth,Barnsley,1,3,A,0,2,...,2.10,1.70,1.89,1.99,2.10,1.85,2.04,1.72,2.25,1.79
9,E2,02/08/2025,15:00,Rotherham,Port Vale,2,1,H,2,0,...,2.03,1.83,2.00,1.89,2.03,1.84,1.94,1.81,2.04,1.93
10,E2,02/08/2025,15:00,Wigan,Northampton,3,1,H,2,0,...,1.90,1.95,2.05,1.85,2.00,1.95,1.93,1.82,1.99,1.98
11,E2,03/08/2025,12:00,Stockport,Bolton,2,0,H,1,0,...,2.20,1.65,1.79,2.11,2.20,1.79,2.05,1.70,2.21,1.82
12,E2,07/08/2025,20:00,Port Vale,Cardiff,0,0,D,0,0,...,2.05,1.80,2.24,1.70,2.05,1.83,1.97,1.78,2.04,1.93
13,E2,09/08/2025,12:30,Peterboro,Luton,0,2,A,0,0,...,2.03,1.83,1.77,2.13,2.03,1.83,1.88,1.79,2.04,1.93
14,E2,09/08/2025,12:30,Reading,Huddersfield,0,2,A,0,0,...,1.93,1.93,2.03,1.86,1.93,1.93,1.89,1.78,2.05,1.94
15,E2,09/08/2025,15:00,AFC Wimbledon,Lincoln,2,0,H,1,0,...,1.70,2.10,1.82,2.09,1.73,2.10,1.70,1.98,1.75,2.29
16,E2,09/08/2025,15:00,Barnsley,Burton,3,2,H,0,2,...,1.80,2.05,1.93,1.95,1.82,2.05,1.76,1.92,1.86,2.13
17,E2,09/08/2025,15:00,Bolton,Plymouth,2,0,H,1,0,...,1.80,2.05,1.95,1.93,1.86,2.05,1.79,1.88,1.92,2.06
18,E2,09/08/2025,15:00,Exeter,Blackpool,4,1,H,2,1,...,1.88,1.98,1.76,2.15,1.88,2.05,1.76,1.97,1.88,2.12
19,E2,09/08/2025,15:00,Leyton Orient,Wigan,2,0,H,1,0,...,2.00,1.85,1.96,1.93,2.00,1.85,1.84,1.83,1.93,2.03
20,E2,09/08/2025,15:00,Mansfield,Doncaster,1,2,A,0,0,...,1.78,2.10,1.83,2.08,1.83,2.10,1.76,2.00,1.80,2.20
21,E2,09/08/2025,15:00,Northampton,Bradford,0,0,D,0,0,...,1.93,1.93,1.98,1.91,1.93,1.93,1.82,1.84,2.02,1.96
22,E2,09/08/2025,15:00,Stevenage,Rotherham,1,0,H,1,0,...,1.88,1.98,1.89,1.99,1.90,2.02,1.80,1.94,1.94,2.05
23,E2,09/08/2025,15:00,Wycombe,Stockport,1,2,A,0,1,...,2.05,1.80,2.21,1.72,2.10,1.80,2.01,1.69,2.14,1.83
24,E2,16/08/2025,12:30,Burton,Port Vale,0,0,D,0,0,...,2.03,1.83,1.88,2.01,2.03,1.92,1.87,1.80,2.03,1.93
25,E2,16/08/2025,12:30,Exeter,Mansfield,1,2,A,0,1,...,2.00,1.85,1.96,1.93,2.00,1.85,1.94,1.80,2.10,1.89
26,E2,16/08/2025,15:00,Barnsley,Bolton,1,1,D,0,0,...,1.83,2.03,1.90,1.98,1.83,2.03,1.74,1.93,1.84,2.12
27,E2,16/08/2025,15:00,Blackpool,Huddersfield,3,2,H,3,2,...,1.70,2.10,1.87,2.02,1.78,2.10,1.71,1.97,1.82,2.15
28,E2,16/08/2025,15:00,Bradford,Luton,2,1,H,1,0,...,1.93,1.93,1.95,1.93,1.93,1.93,1.88,1.80,2.01,1.97
29,E2,16/08/2025,15:00,Cardiff,Rotherham,3,0,H,1,0,...,1.85,2.00,1.99,1.90,1.91,2.00,1.82,1.88,1.92,2.02
30,E2,16/08/2025,15:00,Doncaster,Wycombe,1,1,D,0,0,...,2.05,1.80,1.91,1.97,2.05,1.80,1.90,1.78,2.08,1.90
31,E2,16/08/2025,15:00,Leyton Orient,Stockport,2,2,D,0,2,...,1.88,1.98,2.11,1.80,1.93,1.98,1.86,1.89,1.92,2.06
32,E2,16/08/2025,15:00,Lincoln,Plymouth,3,2,H,1,0,...,1.95,1.90,2.14,1.76,2.00,1.90,1.93,1.80,2.00,1.97
33,E2,16/08/2025,15:00,Reading,AFC Wimbledon,1,2,A,0,1,...,2.08,1.73,1.97,1.92,2.08,1.76,1.93,1.74,2.18,1.83
34,E2,16/08/2025,15:00,Stevenage,Northampton,2,0,H,0,0,...,1.88,1.98,1.95,1.93,1.91,1.98,1.83,1.84,1.96,1.98
35,E2,16/08/2025,15:00,Wigan,Peterboro,2,0,H,2,0,...,1.83,2.03,2.06,1.84,1.88,2.03,1.83,1.90,1.84,2.16
36,E2,19/08/2025,19:45,AFC Wimbledon,Cardiff,0,1,A,0,0,...,1.97,1.77,2.01,1.88,1.97,1.84,1.94,1.72,2.11,1.89
37,E2,19/08/2025,19:45,Huddersfield,Doncaster,2,0,H,0,0,...,1.87,1.87,1.97,1.92,1.87,1.93,1.76,1.90,1.91,2.06
38,E2,19/08/2025,19:45,Luton,Wigan,1,0,H,1,0,...,1.79,1.94,2.07,1.83,1.90,1.94,1.85,1.81,1.94,2.04
39,E2,19/08/2025,19:45,Mansfield,Blackpool,2,0,H,0,0,...,1.89,1.84,1.85,2.04,1.91,2.00,1.82,1.90,1.99,1.97
40,E2,19/08/2025,19:45,Northampton,Lincoln,0,1,A,0,1,...,1.72,2.04,1.96,1.93,1.81,2.04,1.76,1.90,1.86,2.13
41,E2,19/08/2025,19:45,Peterboro,Barnsley,0,1,A,0,1,...,1.87,1.87,1.72,2.21,1.87,2.00,1.80,1.92,1.92,2.02
42,E2,19/08/2025,19:45,Plymouth,Leyton Orient,0,1,A,0,0,...,1.82,1.92,1.70,2.23,1.89,1.92,1.82,1.84,1.94,2.03
43,E2,19/08/2025,19:45,Port Vale,Stevenage,1,2,A,1,0,...,1.77,1.97,1.83,2.06,1.86,2.00,1.79,1.94,1.88,2.10
44,E2,19/08/2025,19:45,Stockport,Bradford,1,2,A,1,0,...,1.89,1.84,2.15,1.76,1.98,1.85,1.91,1.81,1.99,1.98
45,E2,19/08/2025,19:45,Wycombe,Exeter,0,1,A,0,0,...,1.77,1.97,1.89,2.00,1.85,1.97,1.78,1.89,1.88,2.11
46,E2,20/08/2025,20:00,Bolton,Reading,1,1,D,0,0,...,1.93,1.93,1.97,1.92,1.93,1.93,1.85,1.86,2.00,1.96