In [29]:
import pandas as pd

## Import a .csv file from a website
<br>
<br>
Target Link: https://football-data.co.uk/englandm.php

In [30]:
#Reading a file from a website
df_premier25 = pd.read_csv('https://football-data.co.uk/mmz4281/2526/E0.csv')
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
5,E0,16/08/2025,17:30,Wolves,Man City,0,4,A,0,2,...,1.98,1.88,2.07,1.86,2.04,1.88,1.91,1.81,2.05,1.94
6,E0,17/08/2025,14:00,Chelsea,Crystal Palace,0,0,D,0,0,...,1.85,2.00,1.74,2.21,1.85,2.03,1.79,1.97,1.88,2.12
7,E0,17/08/2025,14:00,Nott'm Forest,Brentford,3,1,H,3,0,...,1.88,1.98,2.18,1.76,1.91,1.98,1.86,1.89,1.96,2.03
8,E0,17/08/2025,16:30,Man United,Arsenal,0,1,A,0,1,...,1.88,1.98,1.91,2.01,1.93,1.98,1.86,1.89,2.00,1.99
9,E0,18/08/2025,20:00,Leeds,Everton,1,0,H,0,0,...,2.05,1.80,2.02,1.90,2.05,1.86,1.91,1.78,2.14,1.86

In [31]:
#Renaming Columns
df_premier25.rename(columns={'FTHG': 'home_goals',
                             'FTAG' : 'away_goals'}, inplace=True)
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
5,E0,16/08/2025,17:30,Wolves,Man City,0,4,A,0,2,...,1.98,1.88,2.07,1.86,2.04,1.88,1.91,1.81,2.05,1.94
6,E0,17/08/2025,14:00,Chelsea,Crystal Palace,0,0,D,0,0,...,1.85,2.00,1.74,2.21,1.85,2.03,1.79,1.97,1.88,2.12
7,E0,17/08/2025,14:00,Nott'm Forest,Brentford,3,1,H,3,0,...,1.88,1.98,2.18,1.76,1.91,1.98,1.86,1.89,1.96,2.03
8,E0,17/08/2025,16:30,Man United,Arsenal,0,1,A,0,1,...,1.88,1.98,1.91,2.01,1.93,1.98,1.86,1.89,2.00,1.99
9,E0,18/08/2025,20:00,Leeds,Everton,1,0,H,0,0,...,2.05,1.80,2.02,1.90,2.05,1.86,1.91,1.78,2.14,1.86

## Read .csv from multiple URLS with Pandas
<br>
Link: root + season + league

In [32]:
#Link Structure
# https://football-data.co.uk/mmz4281/2526/E0.csv
#https://football-data.co.uk/mmz4281/2526/E1.csv

"https://football-data.co.uk/mmz4281/" + "2526" + "/" + "E1" + ".csv"

'https://football-data.co.uk/mmz4281/2526/E1.csv'

In [33]:
#Create a Root Variable
root = "https://football-data.co.uk/mmz4281/"

### Multiple Leagues
<br>
https://football-data.co.uk/mmz4281/2526/E0.csv
<br>
https://football-data.co.uk/mmz4281/2526/E1.csv
<br>
https://football-data.co.uk/mmz4281/2526/E2.csv
<br>
https://football-data.co.uk/mmz4281/2526/E3.csv
<br>
https://football-data.co.uk/mmz4281/2526/EC.csv

In [34]:
#Creating a list og leagues
leagues = ["E0", "E1", "E2", "E3", "EC"]
frames = []

#Looping through leagues, read multiple csv and append it to the list
for league in leagues:
    df = pd.read_csv(root + "2526" + "/" + league + ".csv")
    frames.append(df)

In [35]:
#lenght of frames
len(frames)

5

In [36]:
#Show 1st, 2nd and 3rd Element
frames[2]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E2,01/08/2025,20:00,Luton,AFC Wimbledon,1,0,H,0,0,...,1.93,1.93,1.93,1.95,1.98,1.93,1.91,1.82,1.94,2.01
1,E2,02/08/2025,12:30,Cardiff,Peterboro,2,1,H,0,1,...,1.85,2.00,1.87,2.03,1.90,2.00,1.85,1.88,1.93,2.04
2,E2,02/08/2025,15:00,Blackpool,Stevenage,2,3,A,1,2,...,1.93,1.93,1.94,1.94,1.94,1.93,1.84,1.87,1.94,2.04
3,E2,02/08/2025,15:00,Bradford,Wycombe,2,1,H,2,0,...,1.73,2.08,1.90,1.99,1.77,2.20,1.72,2.02,1.80,2.22
4,E2,02/08/2025,15:00,Burton,Mansfield,2,1,H,1,0,...,2.00,1.85,1.69,2.26,2.00,1.85,1.93,1.79,2.04,1.93
5,E2,02/08/2025,15:00,Doncaster,Exeter,1,0,H,0,0,...,2.03,1.83,2.08,1.83,2.03,1.88,1.92,1.82,1.98,1.97
6,E2,02/08/2025,15:00,Huddersfield,Leyton Orient,3,0,H,1,0,...,1.83,2.03,1.96,1.93,1.83,2.03,1.74,1.97,1.86,2.15
7,E2,02/08/2025,15:00,Lincoln,Reading,2,0,H,1,0,...,2.00,1.85,2.03,1.87,2.00,1.85,1.94,1.81,2.04,1.95
8,E2,02/08/2025,15:00,Plymouth,Barnsley,1,3,A,0,2,...,2.10,1.70,1.89,1.99,2.10,1.85,2.04,1.72,2.25,1.79
9,E2,02/08/2025,15:00,Rotherham,Port Vale,2,1,H,2,0,...,2.03,1.83,2.00,1.89,2.03,1.84,1.94,1.81,2.04,1.93
10,E2,02/08/2025,15:00,Wigan,Northampton,3,1,H,2,0,...,1.90,1.95,2.05,1.85,2.00,1.95,1.93,1.82,1.99,1.98
11,E2,03/08/2025,12:00,Stockport,Bolton,2,0,H,1,0,...,2.20,1.65,1.79,2.11,2.20,1.79,2.05,1.70,2.21,1.82
12,E2,07/08/2025,20:00,Port Vale,Cardiff,0,0,D,0,0,...,2.05,1.80,2.24,1.70,2.05,1.83,1.97,1.78,2.04,1.93
13,E2,09/08/2025,12:30,Peterboro,Luton,0,2,A,0,0,...,2.03,1.83,1.77,2.13,2.03,1.83,1.88,1.79,2.04,1.93
14,E2,09/08/2025,12:30,Reading,Huddersfield,0,2,A,0,0,...,1.93,1.93,2.03,1.86,1.93,1.93,1.89,1.78,2.05,1.94
15,E2,09/08/2025,15:00,AFC Wimbledon,Lincoln,2,0,H,1,0,...,1.70,2.10,1.82,2.09,1.73,2.10,1.70,1.98,1.75,2.29
16,E2,09/08/2025,15:00,Barnsley,Burton,3,2,H,0,2,...,1.80,2.05,1.93,1.95,1.82,2.05,1.76,1.92,1.86,2.13
17,E2,09/08/2025,15:00,Bolton,Plymouth,2,0,H,1,0,...,1.80,2.05,1.95,1.93,1.86,2.05,1.79,1.88,1.92,2.06
18,E2,09/08/2025,15:00,Exeter,Blackpool,4,1,H,2,1,...,1.88,1.98,1.76,2.15,1.88,2.05,1.76,1.97,1.88,2.12
19,E2,09/08/2025,15:00,Leyton Orient,Wigan,2,0,H,1,0,...,2.00,1.85,1.96,1.93,2.00,1.85,1.84,1.83,1.93,2.03
20,E2,09/08/2025,15:00,Mansfield,Doncaster,1,2,A,0,0,...,1.78,2.10,1.83,2.08,1.83,2.10,1.76,2.00,1.80,2.20
21,E2,09/08/2025,15:00,Northampton,Bradford,0,0,D,0,0,...,1.93,1.93,1.98,1.91,1.93,1.93,1.82,1.84,2.02,1.96
22,E2,09/08/2025,15:00,Stevenage,Rotherham,1,0,H,1,0,...,1.88,1.98,1.89,1.99,1.90,2.02,1.80,1.94,1.94,2.05
23,E2,09/08/2025,15:00,Wycombe,Stockport,1,2,A,0,1,...,2.05,1.80,2.21,1.72,2.10,1.80,2.01,1.69,2.14,1.83
24,E2,16/08/2025,12:30,Burton,Port Vale,0,0,D,0,0,...,2.03,1.83,1.88,2.01,2.03,1.92,1.87,1.80,2.03,1.93
25,E2,16/08/2025,12:30,Exeter,Mansfield,1,2,A,0,1,...,2.00,1.85,1.96,1.93,2.00,1.85,1.94,1.80,2.10,1.89
26,E2,16/08/2025,15:00,Barnsley,Bolton,1,1,D,0,0,...,1.83,2.03,1.90,1.98,1.83,2.03,1.74,1.93,1.84,2.12
27,E2,16/08/2025,15:00,Blackpool,Huddersfield,3,2,H,3,2,...,1.70,2.10,1.87,2.02,1.78,2.10,1.71,1.97,1.82,2.15
28,E2,16/08/2025,15:00,Bradford,Luton,2,1,H,1,0,...,1.93,1.93,1.95,1.93,1.93,1.93,1.88,1.80,2.01,1.97
29,E2,16/08/2025,15:00,Cardiff,Rotherham,3,0,H,1,0,...,1.85,2.00,1.99,1.90,1.91,2.00,1.82,1.88,1.92,2.02
30,E2,16/08/2025,15:00,Doncaster,Wycombe,1,1,D,0,0,...,2.05,1.80,1.91,1.97,2.05,1.80,1.90,1.78,2.08,1.90
31,E2,16/08/2025,15:00,Leyton Orient,Stockport,2,2,D,0,2,...,1.88,1.98,2.11,1.80,1.93,1.98,1.86,1.89,1.92,2.06
32,E2,16/08/2025,15:00,Lincoln,Plymouth,3,2,H,1,0,...,1.95,1.90,2.14,1.76,2.00,1.90,1.93,1.80,2.00,1.97
33,E2,16/08/2025,15:00,Reading,AFC Wimbledon,1,2,A,0,1,...,2.08,1.73,1.97,1.92,2.08,1.76,1.93,1.74,2.18,1.83
34,E2,16/08/2025,15:00,Stevenage,Northampton,2,0,H,0,0,...,1.88,1.98,1.95,1.93,1.91,1.98,1.83,1.84,1.96,1.98
35,E2,16/08/2025,15:00,Wigan,Peterboro,2,0,H,2,0,...,1.83,2.03,2.06,1.84,1.88,2.03,1.83,1.90,1.84,2.16
36,E2,19/08/2025,19:45,AFC Wimbledon,Cardiff,0,1,A,0,0,...,1.97,1.77,2.01,1.88,1.97,1.84,1.94,1.72,2.11,1.89
37,E2,19/08/2025,19:45,Huddersfield,Doncaster,2,0,H,0,0,...,1.87,1.87,1.97,1.92,1.87,1.93,1.76,1.90,1.91,2.06
38,E2,19/08/2025,19:45,Luton,Wigan,1,0,H,1,0,...,1.79,1.94,2.07,1.83,1.90,1.94,1.85,1.81,1.94,2.04
39,E2,19/08/2025,19:45,Mansfield,Blackpool,2,0,H,0,0,...,1.89,1.84,1.85,2.04,1.91,2.00,1.82,1.90,1.99,1.97
40,E2,19/08/2025,19:45,Northampton,Lincoln,0,1,A,0,1,...,1.72,2.04,1.96,1.93,1.81,2.04,1.76,1.90,1.86,2.13
41,E2,19/08/2025,19:45,Peterboro,Barnsley,0,1,A,0,1,...,1.87,1.87,1.72,2.21,1.87,2.00,1.80,1.92,1.92,2.02
42,E2,19/08/2025,19:45,Plymouth,Leyton Orient,0,1,A,0,0,...,1.82,1.92,1.70,2.23,1.89,1.92,1.82,1.84,1.94,2.03
43,E2,19/08/2025,19:45,Port Vale,Stevenage,1,2,A,1,0,...,1.77,1.97,1.83,2.06,1.86,2.00,1.79,1.94,1.88,2.10
44,E2,19/08/2025,19:45,Stockport,Bradford,1,2,A,1,0,...,1.89,1.84,2.15,1.76,1.98,1.85,1.91,1.81,1.99,1.98
45,E2,19/08/2025,19:45,Wycombe,Exeter,0,1,A,0,0,...,1.77,1.97,1.89,2.00,1.85,1.97,1.78,1.89,1.88,2.11
46,E2,20/08/2025,20:00,Bolton,Reading,1,1,D,0,0,...,1.93,1.93,1.97,1.92,1.93,1.93,1.85,1.86,2.00,1.96

### Multiple Season

In [37]:
#creating a string to work with multiple string
for season in range(20, 26):
    print(str(season) + str(season + 1))

2021
2122
2223
2324
2425
2526

In [38]:
#Creating a list og leagues
leagues = ["E0", "E2", "E3"]
frames = []

#Looping through leagues, read multiple csv and append it to the list
for league in leagues:
    for season in range(20, 26):
        df = pd.read_csv(root + str(season) + str(season + 1) + "/" + league + ".csv")
        df.insert(1, 'season', season)
        frames.append(df)

In [39]:
#Total Dataframes = 6 Season * 3 Leagues = 18 Dataframes
len(frames)

18

In [40]:
#First Dataframe
frames[0]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,20,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,20,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,20,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,20,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,20,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,16:00,Liverpool,Crystal Palace,2,0,H,1,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,20,23/05/2021,16:00,Man City,Everton,5,0,H,2,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,20,23/05/2021,16:00,Sheffield United,Burnley,1,0,H,1,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,20,23/05/2021,16:00,West Ham,Southampton,3,0,H,2,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,20,23/05/2021,16:00,Wolves,Man United,1,2,A,1,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88

In [41]:
#Last Dataframe
frames[-1]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E3,25,02/08/2025,15:00,Accrington,Gillingham,1,1,D,0,...,1.98,1.88,1.76,2.12,1.98,1.88,1.92,1.83,2.09,1.88
1,E3,25,02/08/2025,15:00,Barnet,Fleetwood Town,0,2,A,0,...,2.00,1.85,2.29,1.65,2.08,1.85,2.00,1.74,2.04,1.93
2,E3,25,02/08/2025,15:00,Bristol Rvs,Harrogate,0,1,A,0,...,1.83,2.03,1.85,2.00,1.85,2.03,1.78,1.96,1.88,2.12
3,E3,25,02/08/2025,15:00,Cambridge,Cheltenham,1,0,H,0,...,1.98,1.88,1.88,1.97,1.98,1.88,1.90,1.83,1.98,2.00
4,E3,25,02/08/2025,15:00,Chesterfield,Barrow,1,0,H,1,...,1.78,2.03,1.79,2.06,1.80,2.07,1.73,2.02,1.87,2.13
5,E3,25,02/08/2025,15:00,Colchester,Tranmere,1,1,D,0,...,2.20,1.65,1.97,1.88,2.20,1.68,2.04,1.66,2.31,1.75
6,E3,25,02/08/2025,15:00,Grimsby,Crawley Town,3,0,H,2,...,2.08,1.73,2.02,1.84,2.08,1.83,2.03,1.73,2.14,1.86
7,E3,25,02/08/2025,15:00,Milton Keynes Dons,Oldham,0,0,D,0,...,1.90,1.95,1.79,2.08,1.90,2.05,1.77,1.92,1.92,2.04
8,E3,25,02/08/2025,15:00,Salford,Crewe,1,3,A,1,...,1.90,1.95,1.91,1.94,1.90,1.97,1.82,1.91,1.94,2.02
9,E3,25,02/08/2025,15:00,Shrewsbury,Bromley,0,0,D,0,...,2.10,1.78,2.05,1.81,2.10,1.78,1.95,1.73,2.11,1.88
10,E3,25,02/08/2025,15:00,Walsall,Swindon,2,1,H,1,...,2.00,1.85,2.07,1.80,2.01,1.85,1.89,1.79,2.10,1.88
11,E3,25,02/08/2025,16:00,Newport County,Notts County,1,1,D,0,...,2.03,1.83,2.10,1.76,2.10,1.83,2.03,1.74,2.12,1.86
12,E3,25,09/08/2025,12:30,Notts County,Salford,1,2,A,0,...,1.83,2.03,1.75,2.12,1.83,2.03,1.73,1.96,1.89,2.07
13,E3,25,09/08/2025,12:30,Tranmere,Shrewsbury,4,0,H,2,...,2.05,1.75,1.99,1.87,2.05,1.85,1.97,1.77,2.16,1.85
14,E3,25,09/08/2025,15:00,Barrow,Milton Keynes Dons,0,2,A,0,...,1.90,1.95,1.97,1.88,1.95,1.95,1.89,1.85,2.02,1.93
15,E3,25,09/08/2025,15:00,Bromley,Barnet,2,0,H,1,...,1.78,2.10,1.80,2.07,1.79,2.10,1.76,1.92,1.82,2.21
16,E3,25,09/08/2025,15:00,Cheltenham,Chesterfield,0,2,A,0,...,1.88,1.98,1.86,1.99,1.95,1.98,1.85,1.88,1.98,2.00
17,E3,25,09/08/2025,15:00,Crawley Town,Newport County,1,2,A,0,...,1.83,2.03,1.80,2.07,1.83,2.03,1.74,1.95,1.91,2.05
18,E3,25,09/08/2025,15:00,Crewe,Accrington,2,0,H,2,...,1.80,2.05,1.92,1.93,1.89,2.05,1.81,1.92,1.89,2.11
19,E3,25,09/08/2025,15:00,Fleetwood Town,Bristol Rvs,2,1,H,2,...,2.10,1.78,2.09,1.79,2.10,1.78,1.95,1.72,2.18,1.80
20,E3,25,09/08/2025,15:00,Gillingham,Walsall,1,0,H,0,...,2.00,1.85,2.14,1.75,2.00,1.86,1.83,1.83,2.04,1.93
21,E3,25,09/08/2025,15:00,Harrogate,Grimsby,3,3,D,0,...,2.05,1.80,1.94,1.91,2.05,1.85,1.92,1.76,2.13,1.85
22,E3,25,09/08/2025,15:00,Oldham,Colchester,1,1,D,1,...,2.10,1.70,2.13,1.75,2.10,1.75,1.98,1.71,2.22,1.78
23,E3,25,09/08/2025,15:00,Swindon,Cambridge,3,2,H,2,...,1.88,1.98,1.79,2.08,1.92,1.98,1.79,1.88,1.90,2.04
24,E3,25,16/08/2025,12:30,Chesterfield,Bristol Rvs,3,1,H,1,...,2.03,1.83,1.99,1.87,2.03,1.83,1.91,1.76,2.10,1.88
25,E3,25,16/08/2025,12:30,Oldham,Swindon,1,2,A,1,...,1.70,2.10,1.94,1.91,1.83,2.14,1.71,2.06,1.75,2.27
26,E3,25,16/08/2025,15:00,Barnet,Walsall,1,2,A,1,...,1.83,2.03,1.90,1.95,1.85,2.03,1.75,1.92,1.86,2.11
27,E3,25,16/08/2025,15:00,Barrow,Notts County,2,1,H,1,...,2.03,1.83,1.98,1.88,2.03,1.85,1.96,1.80,2.05,1.93
28,E3,25,16/08/2025,15:00,Bromley,Fleetwood Town,2,2,D,1,...,1.98,1.88,2.07,1.80,1.98,1.88,1.84,1.84,1.96,1.99
29,E3,25,16/08/2025,15:00,Cambridge,Harrogate,1,1,D,1,...,1.88,1.98,1.89,1.96,1.88,1.98,1.84,1.84,1.97,1.98
30,E3,25,16/08/2025,15:00,Crewe,Crawley Town,1,0,H,1,...,2.03,1.78,2.02,1.84,2.03,1.78,1.96,1.72,2.02,1.90
31,E3,25,16/08/2025,15:00,Grimsby,Newport County,2,1,H,1,...,2.05,1.80,2.04,1.83,2.05,1.81,1.92,1.76,2.13,1.86
32,E3,25,16/08/2025,15:00,Milton Keynes Dons,Cheltenham,5,0,H,3,...,2.03,1.75,2.00,1.85,2.03,1.85,1.90,1.79,2.14,1.86
33,E3,25,16/08/2025,15:00,Salford,Accrington,2,1,H,2,...,1.95,1.90,1.83,2.03,1.95,1.95,1.85,1.89,1.97,2.01
34,E3,25,16/08/2025,15:00,Shrewsbury,Colchester,0,2,A,0,...,1.78,2.10,1.81,2.06,1.78,2.10,1.75,2.01,1.78,2.24
35,E3,25,16/08/2025,15:00,Tranmere,Gillingham,1,1,D,0,...,1.85,2.00,1.85,2.01,1.85,2.00,1.73,1.95,1.91,2.08
36,E3,25,19/08/2025,19:30,Newport County,Salford,0,1,A,0,...,1.88,1.98,1.72,2.17,1.88,2.05,1.81,1.93,1.94,2.04
37,E3,25,19/08/2025,19:45,Bristol Rvs,Oldham,0,0,D,0,...,1.80,2.03,1.85,2.01,1.81,2.03,1.73,1.95,1.84,2.16
38,E3,25,19/08/2025,19:45,Cheltenham,Bromley,1,2,A,0,...,1.85,1.95,1.84,2.02,1.85,1.99,1.79,1.89,1.93,2.06
39,E3,25,19/08/2025,19:45,Colchester,Cambridge,1,2,A,1,...,1.82,2.00,1.86,1.99,1.85,2.00,1.81,1.93,1.91,2.06
40,E3,25,19/08/2025,19:45,Crawley Town,Milton Keynes Dons,1,1,D,1,...,2.03,1.78,2.03,1.83,2.07,1.78,2.02,1.72,2.21,1.82
41,E3,25,19/08/2025,19:45,Fleetwood Town,Crewe,1,4,A,0,...,1.85,1.95,1.93,1.93,1.85,1.95,1.83,1.91,1.91,2.06
42,E3,25,19/08/2025,19:45,Gillingham,Chesterfield,4,1,H,1,...,1.92,1.87,1.83,2.03,1.92,1.93,1.83,1.83,1.99,1.96
43,E3,25,19/08/2025,19:45,Harrogate,Barrow,1,0,H,1,...,1.77,2.05,1.69,2.22,1.77,2.10,1.70,1.98,1.84,2.16
44,E3,25,19/08/2025,19:45,Swindon,Barnet,0,2,A,0,...,1.77,2.05,1.71,2.18,1.83,2.05,1.76,2.00,1.93,2.04
45,E3,25,19/08/2025,20:00,Walsall,Grimsby,0,1,A,0,...,1.82,2.00,1.80,2.07,1.83,2.00,1.79,1.95,1.89,2.09
46,E3,25,20/08/2025,19:45,Notts County,Shrewsbury,4,1,H,2,...,2.05,1.80,2.08,1.78,2.05,1.83,1.99,1.76,2.16,1.84

## Organize all the data in a Dictionary

In [42]:
#Create a country with the original name of leagues as key
dict_countries = {"Spanish La Liga" : "SP1", "Spanish Segunda Division" : "SP2",
                  "English Premier League" : "E0", "English League 1" : "E2", "English League 2" : "E3"}

In [43]:
#Get a Dictionary Element
dict_countries['Spanish La Liga']

'SP1'

In [44]:
#How iteration in dictionaries work
for league in dict_countries:
    print(league)

Spanish La Liga
Spanish Segunda Division
English Premier League
English League 1
English League 2

In [45]:
#How iteration in dictionaries work
for league in dict_countries:
    print(dict_countries[league])

SP1
SP2
E0
E2
E3

In [46]:
dict_historical_data = {}

#Creating a list og leagues
#leagues = ["E0", "E2", "E3"]

#Looping through key elements
for league in dict_countries:
    frames = [] #Everytime this loops starts list initializes
    for season in range(20, 26):
        df = pd.read_csv(root + str(season) + str(season + 1) + "/" + dict_countries[league] + ".csv")
        df.insert(1, 'season', season)
        frames.append(df)
    df_concat = pd.concat(frames) # Concatinates all the Dataframes of a league from diff. seasons
    dict_historical_data[league] = df_concat #Adds all the data into a Dictionary

In [48]:
#Show dataframe inside dist_historical_data
dict_historical_data['English League 1']

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,E2,20,12/09/2020,15:00,Accrington,Peterboro,2,0,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E2,20,12/09/2020,15:00,Crewe,Charlton,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E2,20,12/09/2020,15:00,Doncaster,Milton Keynes Dons,1,1,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E2,20,12/09/2020,15:00,Fleetwood Town,Burton,2,1,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E2,20,12/09/2020,15:00,Gillingham,Hull,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,E2,25,19/08/2025,19:45,Plymouth,Leyton Orient,0,1,A,0,...,2.20,3.10,3.50,2.20,3.20,3.6,2.15,3.10,3.50,2.15
43,E2,25,19/08/2025,19:45,Port Vale,Stevenage,1,2,A,1,...,2.75,2.60,3.00,2.88,2.62,3.0,2.87,2.62,3.00,2.87
44,E2,25,19/08/2025,19:45,Stockport,Bradford,1,2,A,1,...,3.70,1.90,3.40,4.10,1.95,3.4,4.00,1.95,3.40,3.90
45,E2,25,19/08/2025,19:45,Wycombe,Exeter,0,1,A,0,...,4.90,1.62,3.75,5.50,1.67,3.8,5.00,1.67,3.80,5.00
46,E2,25,20/08/2025,20:00,Bolton,Reading,1,1,D,0,...,5.20,1.53,4.33,5.50,1.55,4.4,5.50,1.55,4.33,5.25